$!

	Template for the lower menu bar in the header
	
	see PageParameters class for documentation of full set of arguments
!$
<div class="lowermenubar">
	 <div class="lowermenubarCenter navcenter">
         <div>
             <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="titleLeft"><div /></td>
                    <td class="titleCenter"><div>$pageTitle$</div></td>
                    <td class="titleRight"><div /></td>
                 </tr>
             </table>
         </div>
    </div>
    <div class="lowermenubarRight">
        <div class="searchContainer">
            $searchfield$
        </div>
    </div>
</div>